# Generated by Django 5.1.6 on 2025-02-18 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itens',
            old_name='precouni',
            new_name='preco_unitario',
        ),
        migrations.RenameField(
            model_name='itens',
            old_name='quant',
            new_name='quantidade',
        ),
        migrations.RenameField(
            model_name='pedidos',
            old_name='data',
            new_name='data_pedido',
        ),
    ]
